// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6JU3UZ95IEpf-HrSNZvbfLd8V8qaOykI',
    appId: '1:763314098857:web:0d59eaabced71e3c91cfb8',
    messagingSenderId: '763314098857',
    projectId: 'gourmentcoffee-6a612',
    authDomain: 'gourmentcoffee-6a612.firebaseapp.com',
    storageBucket: 'gourmentcoffee-6a612.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfytLxfrr78jdSKYd2fR7tdjFqx7HqNu8',
    appId: '1:763314098857:android:0f2ba834bc09bfcb91cfb8',
    messagingSenderId: '763314098857',
    projectId: 'gourmentcoffee-6a612',
    storageBucket: 'gourmentcoffee-6a612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPFQZp3yrln8z5zMh87lUpWNwMauyI0YM',
    appId: '1:763314098857:ios:3195f81c105acec091cfb8',
    messagingSenderId: '763314098857',
    projectId: 'gourmentcoffee-6a612',
    storageBucket: 'gourmentcoffee-6a612.appspot.com',
    iosClientId: '763314098857-lcedl8t3vpb75jfkiij2v3ac6r2mb6aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gourmentcofe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPFQZp3yrln8z5zMh87lUpWNwMauyI0YM',
    appId: '1:763314098857:ios:3195f81c105acec091cfb8',
    messagingSenderId: '763314098857',
    projectId: 'gourmentcoffee-6a612',
    storageBucket: 'gourmentcoffee-6a612.appspot.com',
    iosClientId: '763314098857-lcedl8t3vpb75jfkiij2v3ac6r2mb6aq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gourmentcofe',
  );
}
